title: ∀∃ Portfolio
description: A collection of my works
theme: just-the-docs

url: https://random-entity.github.io/pf

aux_links:
  "GitHub":
    - "https://github.com/random-entity"
aux_links_new_tab: false

collections:
  kr:
    permalink: "/:collection/:path/"
    output: true
  en:
    permalink: "/:collection/:path/"
    output: true
  jp:
    permalink: "/:collection/:path/"
    output: true
just_the_docs:
  collections:
    kr:
      name: Korean
      nav_fold: true
    en:
      name: English
      nav_fold: true
    jp:
      name: Japanese
      nav_fold: true

heading_anchors: true
callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  note:
    title: Note
    color: purple
  warning:
    title: Warning
    color: red